// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    {
      type: 'doc',
      id: 'concepts',
      label: 'Concepts & glossary',
    },
    {
      type: 'doc',
      id: 'quickstart',
      label: 'Quickstart',
    },
    {
      type: 'category',
      label: 'Widgets',
      link: { type: 'doc', id: 'widgets/index' },
      items: [
        'widgets/registration-widget',
        'widgets/calendar-widget',
        'widgets/map-widget',
        'widgets/profile-widget',
        'widgets/video-widget',
        'widgets/checkout-widget',
      ],
    },
    {
      type: 'category',
      label: 'API',
      link: { type: 'doc', id: 'api/index' },
      items: [
        'api/authentication',
        'api/errors',
        {
          type: 'category',
          label: 'API Operations',
          link: {
            type: 'generated-index',
            title: 'API Operations',
            description: 'Full reference of all Zooza REST API endpoints.',
            slug: '/api/reference',
          },
          // Autogenerated from docs/api/reference/ — populated by `npm run gen-api-docs`
          items: [{ type: 'autogenerated', dirName: 'api/reference' }],
        },
      ],
    },
    {
      type: 'doc',
      id: 'enums',
      label: 'Enums reference',
    },
  ],
};

module.exports = sidebars;
